---
understate_threshold: 10000
understate_factor: 2
per_page: 20   # with per_page = 1000, client index takes more than a minute => nginx timeout!
default_status: alle
default_role: Kundinnen
default_mailing: egal
show_revenue: admin
sales_since: 2001.01.01.
